In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cu124


In [3]:
!nvidia-smi

Wed Jan  8 12:09:46 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   44C    P8              3W /   50W |     449MiB /   4096MiB |     21%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [8]:
## Introduction to Tensors

#Creating Tensors

#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [9]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [14]:
#vector
vector = torch.tensor([7,7])
vector
vector.ndim

1

In [16]:
matrix = torch.tensor([[1,2], [3,4]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [21]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [2,3,4]],
                       [[2,3,4],
                        [3,4,5],
                        [4,5,6]]])
# TENSOR.ndim
TENSOR.shape

torch.Size([2, 3, 3])

Random tensors are important caz the way neural networks learn is that they start with tensors full of random numbers and then adjust the random numbers to better represnt the data

In [24]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(2,5,5)
random_tensor

tensor([[[0.5454, 0.8459, 0.2828, 0.4588, 0.7690],
         [0.7572, 0.2321, 0.7312, 0.2142, 0.7427],
         [0.8297, 0.4467, 0.7116, 0.7407, 0.2773],
         [0.0379, 0.4542, 0.2869, 0.6940, 0.0473],
         [0.3895, 0.5753, 0.9455, 0.9819, 0.8395]],

        [[0.0943, 0.7201, 0.7422, 0.8825, 0.0884],
         [0.2915, 0.6624, 0.6669, 0.6818, 0.4117],
         [0.2249, 0.6309, 0.8559, 0.6141, 0.3052],
         [0.6277, 0.0856, 0.4812, 0.8983, 0.2918],
         [0.2061, 0.5741, 0.7764, 0.3146, 0.4936]]])

In [25]:
#create a random tensor with similarr shape to image
rand_img_size_tensor = torch.rand(size=(224,224,3))
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
### Zeros and ones

#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [33]:
###Create a range of tensors and tensors-lke

#use torch.arange
one_to_ten = torch.arange(0, 10, 0.5)

In [35]:
#creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
###tensor datatype

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, 
                               device= "cuda",
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [41]:
float_32_tensor.device

device(type='cuda', index=0)

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [40]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [44]:
#manipulatng tensors (tensor operations)
# # Tensor operations include
# 1. Addtion
# 2. subtraction
# 3. multiplication
# 4. Division 
# 5. matrix mul

In [45]:
#addd
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [46]:
#mul
tensor * 10

tensor([10, 20, 30])

In [50]:
#dot product

tensor @ tensor

tensor(14)

In [48]:
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
##one of the most common errors is shape errors
torch.rand(3,4) @ torch.rand(3,4)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [52]:
torch.rand(3,4) @ torch.rand(4,3)

tensor([[1.0704, 1.7138, 1.2257],
        [0.7309, 1.1545, 0.6439],
        [0.4323, 0.9523, 1.2761]])

In [58]:
## matmul can be written as mm so can use torch.mm

#to fix tensor shape issues, we can manipulate the shape of one of the tensor using transpose

ten_b = torch.rand(3,2)
ten_b.T.shape


torch.Size([2, 3])

In [59]:
# finding min, max, mean, sum etc (tensor aggregation)

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [63]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [64]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [65]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
### reshaping, stacking, squeeing and unsqueezing tensors

# Reshape - reshapes the input tensor to a defined shape
# view - return a view of an input tensor of a certain shape but keep the same memory as the original

In [77]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [78]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [80]:
## changing z changes x (because a view of a tensor shares the same memory as the original x)
z[:, 0] = 5.
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [85]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [87]:
x_squeeze = torch.squeeze(x_reshaped)
x_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
x_squeeze.unsqueeze(dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [93]:
x_original = torch.rand(224,224,3)
x_original.shape

torch.Size([224, 224, 3])

In [94]:
x_premuted = x_original.permute(2, 0 , 1)
x_premuted.shape

torch.Size([3, 224, 224])

In [95]:
## Indexing
# Indexing with PyTorch is similar to indexing in NumPy
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [96]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
x[0,0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [99]:
x[0,0,1]

tensor(2)

In [100]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [101]:
x[0,0,:]

tensor([1, 2, 3])

In [104]:
import torch
import numpy as np

array = np.arange(1,0, 8.0)
tensor = torch.from_numpy(array)
array  , tensor

array([], dtype=float64)

In [105]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B

(tensor([[0.9653, 0.2766, 0.0435, 0.0963],
         [0.9580, 0.1782, 0.6184, 0.8870],
         [0.8143, 0.7816, 0.9942, 0.4119]]),
 tensor([[0.4401, 0.1872, 0.6200, 0.5923],
         [0.2414, 0.2688, 0.8392, 0.2306],
         [0.3903, 0.2597, 0.9994, 0.3538]]))

In [107]:
#lets make random but reproducible tensors
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
random_tensor_C, random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [108]:
import torch
torch.cuda.is_available()

True

In [109]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [111]:
torch.cuda.device_count()

1

In [112]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [113]:
tensor_to_gpu = tensor.to(device=device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [114]:
# tensor_to_gpu.numpy() will not work since numpy doesnt work on gpu, so u have to change device o cpu and then call numpy
tensor_back_cpu = tensor_to_gpu.to('cpu').numpy()
tensor_back_cpu

array([1, 2, 3], dtype=int64)